### ISSUE TITLE
Cant build example

### ISSUE THREAD

**Issue by lukaseller** [PyO3/pyo3#300]
I have a problem with the following [example]( https://pyo3.rs/master/get_started.html) .

I copied the source code in my lib.rs 

```
#![feature(specialization)]

#[macro_use]
extern crate pyo3;

use pyo3::prelude::*;

#[pyfunction]
/// Formats the sum of two numbers as string
fn sum_as_string(a: usize, b: usize) -> PyResult<String> {
    Ok((a + b).to_string())
}

/// This module is a python moudle implemented in Rust.
#[pymodule]
fn rust_py(py: Python, m: &PyModule) -> PyResult<()> {
    m.add_wrapped(wrap_function!(sum_as_string))?;

    Ok(())
}
```
And set my cargo.toml file to:

```
[package]
name = "rust-py"
version = "0.1.0"

[lib]
name = "rust_py"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.5.2"
features = ["extension-module"]
```

When I do : 

> cargo rustc --release -- -C link-arg=-undefined -C link-arg=dynamic_lookup

I get the following error regarding the pymodule argument:

> error[E0658]: The attribute `pymodule` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)

My setup:
- MacOs 10.14
- rustc 1.32.0-nightly

Any ideas what could be the issue? Thanks

**Comment by konstin** [comment]
The problem is that you're using the documentation for master, while building on stable (0.5.2). [stable docs](https://pyo3.rs/v0.5.2/)

**Comment by lukaseller** [comment]
Thank you for your help!
But it seems that there is another issue: 

```
error[E0119]: conflicting implementations of trait `python::IntoPyDictPointer` for type `(_, _)`:
   --> /Users/lukas/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.3.2/src/objects/dict.rs:246:1
    |
231 | / impl <K, V, I> IntoPyDictPointer for I

232 | | where
233 | |     K: ToPyObject,
234 | |     V: ToPyObject,
...   |
243 | |     }
244 | | }
    | |_- first implementation here
245 |
246 |   impl<K: ToPyObject, V: ToPyObject> IntoPyDictPointer for (K, V) {
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `(_, _)`
    |
    = note: upstream crates may add new impl of trait `std::iter::Iterator` for type `(_, _)` in future versions
```

This seems to be related to [this issue](https://github.com/PyO3/pyo3/issues/197).
It seems that the stable documentation does still have version 0.3 in the dependencies for the [getting started example](https://pyo3.rs/v0.5.2/).

**Comment by lukaseller** [comment]
Update: It seems to be working with version `version = "0.5.2"`
I guess changing this to the current version could safe a lot of confusing for people how are just starting out. 

Thank you anyway for your great work here :)

**Comment by shawn-xy** [comment]
Met the same issue. I made it work with git clone the master and add
`path = "/path/to/the/cloned/repo"` .

**Comment by konstin** [comment]
I'm sorry for the inconvenience; The problem is that the documentation references 0.3 in the 0.5  documentation. This has been fixed in master (#293), but we can't just make a new release since we've already merged some breaking changes for 0.6.

@shawn-xy Please don't do that. Cargo has sufficient support for git dependencies and for [overriding dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#overriding-dependencies), which will avoid accidentally forking pyo3.
