### ISSUE TITLE
Regression using `Self` inside `#[pymethods]` arguments

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#1070]
This snippet used to work on pyo3 `0.8`:

```
#[pyclass]
struct MyClass { }

#[pymethods]
impl MyClass {
    fn takes_self(&self, other: &Self) { }
}
```

With `0.11.1` it fails with:

```
error[E0411]: cannot find type `Self` in this scope=================>  ] 35/36: ...
  --> src/lib.rs:14:34
   |
14 |     fn takes_self(&self, other: &Self) { }
   |                                  ^^^^ `Self` is only available in impls, traits, and type definitions
```

This was originally reported in https://github.com/PyO3/pyo3/pull/791#issuecomment-664374894, which also identifies possible guilty line.
