### PR TITLE
ffi-check: ignore mingw types

### PR DESCRIPTION
**Pull request by Icxolu**
I commonly develop using a mingw toolchain and noticed that for me ffi-check started failing locally after #5918 with this error:
```txt
error[E0080]: index out of bounds: the length is 1 but the index is 8
    --> ...\pyo3\pyo3-ffi-check\target\x86_64-pc-windows-gnullvm\debug\build\pyo3-ffi-check-definitions-10e98362a5f4c68d\out/bindings.rs:6511:5
     |
6511 |     ["Alignment of __mingw_ldbl_type_t"][::std::mem::align_of::<__mingw_ldbl_type_t>() - 8usize];
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ evaluation of `bindgen::_` failed here

For more information about this error, try `rustc --explain E0080`.
error: could not compile `pyo3-ffi-check-definitions` (lib) due to 1 previous error
```

I think this is just caused because bindgen generates some checks for mingw internal types, which we can simply ignore. 

This will have no effect on CI (and I don't think we need to extend it as it is not commonly used), but it might be nice to fix it anyway.

### CODE REVIEW

**Review by ngoldbaum — APPROVED** [review]
I'm ok with ignoring mingw-specific weirdness.
