### PR TITLE
internal: fix python abi library name for mingw

### LINKED ISSUE #6157: 0.28 raw-dylib linking regressed MSYS2/MinGW (libpython3X.dll vs python3X.dll)
## Summary

PyO3 0.28 (PR #5866) switched Windows linking to Rust's `raw-dylib` and hardcoded the imported DLL name as `python3X.dll`. This regressed MSYS2/MinGW (`*-pc-windows-gnu`) downstream builds, where the Python DLL is named `libpython3X.dll` (Unix-style `lib` prefix). Every Python C-API symbol now comes back undefined at link time.

This was already flagged by @ognevny on the merged PR but doesn't have a tracking issue:
https://github.com/PyO3/pyo3/pull/5866#issuecomment-4702708928

> hi, this change seem to regress MINGW downstream builds, probably because we use `libpython3.dll` library (it uses the lib prefix like any other UNIX environment)

The previous escape hatch (`generate-import-lib`) is now a deprecated no-op per the 0.28 changelog, so downstreams have no way to opt out aside from pinning `pyo3 = "0.27.x"`.

## Downstream impact

- **blake3-py 1.0.9** (which bumped to pyo3 0.28): https://github.com/oconnor663/blake3-py/issues/109
- **borgbackup CI on MSYS2 UCRT64**, failing log: https://github.com/borgbackup/borg/actions/runs/27977945398/job/82800454532
- The matching borg build on **pyo3 0.27 / blake3-py 1.0.8** succeeds on the same runner: https://github.com/borgbackup/borg/actions/runs/27978763145/job/82803271025

Truncated link error from the failing log:

```
ld.exe: ...libpyo3-*.rlib: undefined reference to `PyUnicode_FromStringAndSize'
ld.exe: ...libpyo3-*.rlib: undefined reference to `Py_GenericAlias'
ld.exe: ...libpyo3-*.rlib: undefined reference to `PyDict_New'
... (many more)
collect2.exe: error: ld returned 1 exit status
```

## Proposed direction

Emit the `lib`-prefixed DLL name in `extern_python_dll!` / the `raw-dylib` import on `*-pc-windows-gnu` targets when the Python install is the MSYS2-style one — or expose a build-script knob so downstreams can override the import name.

### PR DESCRIPTION
**Pull request by ognevny**
usually mingw version of python are shipped with `lib` prefix, so we need to add it for proper linking

fixes #6157

### CODE REVIEW

**Comment by ognevny** [comment]
it seems that this didn't fix downstream builds. for me pyca/cryptography still fail :(

@messense is there any place I missed?

**Comment by messense** [comment]
I think we need to change here https://github.com/PyO3/pyo3/blob/b3aa7da7c5a89a4234b48341621b36b185a41236/pyo3-ffi/src/impl_/macros.rs#L255

**Comment by ognevny** [comment]
> I think we need to change here
> 
> https://github.com/PyO3/pyo3/blob/b3aa7da7c5a89a4234b48341621b36b185a41236/pyo3-ffi/src/impl_/macros.rs#L255

that didn't help too...

https://github.com/msys2/MINGW-packages/actions/runs/28220768771/job/83601338236?pr=29942

**Comment by ognevny** [comment]
probably adding +verbatim will help: https://github.com/microsoft/windows-rs/blob/f5c410d9328702a879af321107bb5334a129e991/crates/libs/link/src/lib.rs#L15

that didn't help too

**Comment by ognevny** [comment]
#6164 did it better
