### ISSUE TITLE
Cannot implement `__len__` classmethod (0.21+)

### ISSUE THREAD

**Issue by timkpaine** [PyO3/pyo3#4640]
### Bug Description

This used to work in `pyo3<0.21`:

```rust
    #[classmethod]
    fn __len__(cls: &Bound<'_, PyType>) -> PyResult<usize> {
        Ok(0)
    }
```

```raw
error[E0425]: cannot find value `_slf_ref` in this scope
  --> lib1-py/src/lib.rs:15:1
   |
15 | #[pymethods]
   | ^^^^^^^^^^^^ not found in this scope
```

### Steps to Reproduce

Include the above block in any `#[pymethods]` block

### Backtrace

```shell
error[E0425]: cannot find value `_slf_ref` in this scope
  --> lib1-py/src/lib.rs:15:1
   |
15 | #[pymethods]
   | ^^^^^^^^^^^^ not found in this scope
```

### Your operating system and version

macOS 15.0.1

### Your Python version (`python --version`)

Python 3.11.10

### Your Rust version (`rustc --version`)

rustc 1.79.0 (129f3b996 2024-06-10)

### Your PyO3 version

0.22.5

### How did you install python? Did you use a virtualenv?

brew install python@3.11, pip install pyo3

**Comment by LilyFoote** [comment]
Defining `__len__` as a `@classmethod` seems very unusual to me. What's your use case?

**Comment by timkpaine** [comment]
Not unusual at all for certain types:

```python
from enum import Enum, auto

class MyEnum(Enum):
    A = auto()
    B = auto()
    
print(len(MyEnum))
```

**Comment by timkpaine** [comment]
> I think you'll need #906 to be implemented to achieve this in PyO3.

Or downgrade to `0.19`, which is the more annoying bit as this used to work fine

**Comment by davidhewitt** [comment]
Agreed this is a legitimate bug.

From a quick test, it seems like Python allows most (all?) the dunder methods to be `@classmethod` or even `@staticmethod`, so this is simply just a case which we should add tests for and support 👍

**Comment by Icxolu** [comment]
I attempted a fix in #4654.
