### PR TITLE
internal: preliminary fixes for PyPy 3.12

### LINKED ISSUE #6244: Avoid PyUnstable* API functions on PyPy
### Bug Description

I have started working on pypy for python3.12 and fail tests because `PyUnstable_InterpreterFrame_GetCode` is missing.

PyPy is unlikely to implement `PyUnstable_InterpreterFrame_GetCode` and other `PyUnstable` C-API interfaces going forward. Would that be a major incompatibility? As far as I can tell, it is used for debuggers and not for common code.

### Steps to Reproduce

Test with pypy-3.12-nightly as I do in [pypy/binary-testing](https://github.com/pypy/binary-testing/actions/runs/30212546282/job/89821126491)

### Backtrace

```shell
error[E0425]: cannot find type `_PyInterpreterFrame` in this scope
  --> pyo3-ffi/src/cpython/pyframe.rs:69:60
   |
69 |     pub fn PyUnstable_InterpreterFrame_GetCode(frame: *mut _PyInterpreterFrame) -> *mut PyObject;
   |                                                            ^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `_PyInterpreterFrame` in this scope
  --> pyo3-ffi/src/cpython/pyframe.rs:72:61
   |
72 |     pub fn PyUnstable_InterpreterFrame_GetLasti(frame: *mut _PyInterpreterFrame) -> c_int;
   |                                                             ^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `_PyInterpreterFrame` in this scope
  --> pyo3-ffi/src/cpython/pyframe.rs:75:60
   |
75 |     pub fn PyUnstable_InterpreterFrame_GetLine(frame: *mut _PyInterpreterFrame) -> c_int;
   |                                                            ^^^^^^^^^^^^^^^^^^^ not found in this scope
```

### Your operating system and version

ubuntu 26.04

### Your Python version (`python --version`)

pypy 3.12

### Your Rust version (`rustc --version`)

rustc 1.97.1

### Your PyO3 version

HEAD

### How did you install python? Did you use a virtualenv?

from the actions/setup-python

### Additional Info

Thanks!

### LINKED ISSUE #6345: PyPy 3.12 is missing c_int
### Bug Description

In PR #5547 the addition of PyDict_ClearWatcher needs c_int. But it is conditionally removed for pypy 3.12 in pyo3-ffi/src/cpython/dictobject.rs. Now that I am [testing pyO3 on pypy3.12](https://github.com/pypy/binary-testing/actions/runs/32614391431/job/97132581313) in preparation for a first 3.12 release, I see the failure. 

### Steps to Reproduce

1. Download a [nightly pypy3.12](https://buildbot.pypy.org/nightly/py3.12/)
2. run pyo3 tests

### Backtrace

```shell
Error[E0425]: cannot find type `c_int` in this scope
   --> pyo3-ffi/src/cpython/dictobject.rs:134:44
    |
134 |     pub fn PyDict_ClearWatcher(watcher_id: c_int) -> c_int;
    |                                            ^^^^^ not found in this scope
    |
note: found an item that was configured out
   --> pyo3-ffi/src/cpython/abstract_.rs:5:16
    |
  4 | #[cfg(not(Py_3_11))]
    |          --------- the item is gated here
  5 | use core::ffi::c_int;
    |                ^^^^^
note: found an item that was configured out
   --> pyo3-ffi/src/cpython/dictobject.rs:14:16
    |
 13 | #[cfg(all(not(PyPy), Py_3_12))]
    |              ------ the item is gated here
 14 | use core::ffi::c_int;
    |                ^^^^^
help: consider importing one of these type aliases
    |
  1 + use std::ffi::c_int;
    |
  1 + use std::os::raw::c_int;
    |
  1 + use core::ffi::c_int;
    |
  1 + use libc::c_int;
```

### Your operating system and version

Ubuntu linux-x86_64 24.04

### Your Python version (`python --version`)

pypy3.12

### Your Rust version (`rustc --version`)

rustc 1.98.0 (88d9e12ae 2026-08-18)

### Your PyO3 version

HEAD

### How did you install python? Did you use a virtualenv?

downloaded nightly build

### Additional Info

I am not a rust expert, but I think the problem is https://github.com/PyO3/pyo3/blob/e2b68f3b17f74d2a7b67f7d31aad248738b8f790/pyo3-ffi/src/cpython/dictobject.rs#L13-L15

### PR DESCRIPTION
**Pull request by davidhewitt**
Fixes #6345 
Fixes #6244

This lands some preliminary fixes to get the PyPy 3.12 test suite moving further along based on local testing.

### CODE REVIEW

File: pyo3-ffi/src/object.rs [hunk 1]
```diff
@@ -390,7 +390,6 @@ extern_libpython! {
     ) -> *mut PyObject;
 
     #[cfg(Py_3_12)]
-    #[cfg_attr(PyPy, link_name = "PyPyObject_GetTypeData")]
```
Comment (bschoenmaeckers) [inline pyo3-ffi/src/object.rs:393]: Is this intentional? Does it not have the PyPy prefix?

Comment (mattip) [reply pyo3-ffi/src/object.rs:393]: Yes, this is intentional. PyPy3.12 is moving to a model where the limited API interfaces will match 1:1 CPython, in preparation for being able to use abi3 c-extension modules without recompilation. There is more to do, we have not released 3.12 yet.

Comment (davidhewitt) [reply pyo3-ffi/src/object.rs:393]: Yes, I found some mention of this at https://github.com/pypy/pypy/issues/3397#issuecomment-4907956162

**Review by bschoenmaeckers — APPROVED** [review]
