### ISSUE TITLE
Confusing error message when using #[pyclass] with a struct called Probe

### ISSUE THREAD

**Issue by Tiwalun** [PyO3/pyo3#4792]
### Bug Description

The following code fails to compile, with a somewhat confusing error message:

```rust
use pyo3::prelude::*;

#[pyclass]
struct Probe {}
```

The error message is:

```
error[E0782]: expected a type, found a trait
 --> src/lib.rs:4:8
  |
4 | struct Probe {}
  |        ^^^^^
  |
help: you can add the `dyn` keyword if you want a trait object
  |
4 | struct dyn Probe {}
  |        +++

For more information about this error, try `rustc --explain E0782`.
error: could not compile `pyo3-repro` (lib) due to 1 previous error
```

rust-analyzer suggests that this might be due to the `trait Probe` here:
https://github.com/PyO3/pyo3/blob/926f5cf8e427d08b0a4670d89e3b0f342c299489/src/impl_/pyclass/probes.rs#L16

I'm not sure if this can be fixed, but it would be nice to at least have a clearer error message to indicate that the struct can't be called `Probe`. 

### Steps to Reproduce

Compile the code mentioned above.

### Your operating system and version

Ubuntu 24.04

### Your Python version (`python --version`)

Python 3.12.3

### Your Rust version (`rustc --version`)

rustc 1.83.0 (90b35a623 2024-11-26)

### Your PyO3 version

0.23.3

### How did you install python? Did you use a virtualenv?

apt

### Additional Info

This was observed when updating PyO3 from version 0.21 to 0.22, so it seems to have changed in version 0.22.

**Comment by Icxolu** [comment]
Thanks for reporting, should be fixed by #4794.

**Comment by maurosilber** [comment]
This is still an issue with PyO3 `0.28.2`.

```rust
#[::pyo3::pyclass(get_all)]
pub struct Probe {
    field: u8,
}
```
`expected a type, found a trait`


Doing a macro expansion, the issue is with the following:
```rust
fn items_iter() -> ::pyo3::impl_::pyclass::PyClassItemsIter {
        use ::pyo3::impl_::pyclass::*;
```
that brings into scope everying from the `pyclass` module.
