### ISSUE TITLE
pyo3 0.18.1 doesn't compile with rustc 1.48

### ISSUE THREAD

**Issue by danielabrozzoni** [PyO3/pyo3#2965]
### Bug Description

The readme states that pyo3 supports rust `1.48+`, but compilation fails because of `parking_lot_core-0.9.7`. The latest version that supports rust 1.48 seems to be "0.15.2"

### Steps to Reproduce

Include in your README.md
```
pyo3 = { version = "0.18.1", features = ["auto-initialize"] }
```
and try to build it with rustc `1.48`

### Backtrace

```shell
$ cargo build
   Compiling parking_lot_core v0.9.7
   Compiling pyo3-ffi v0.18.1
   Compiling pyo3 v0.18.1
error[E0658]: use of unstable library feature 'renamed_spin_loop'
 --> /home/daniela/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.9.7/src/spinwait.rs:9:5
  |
9 | use core::hint::spin_loop;
  |     ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #55002 <https://github.com/rust-lang/rust/issues/55002> for more information

error[E0658]: use of unstable library feature 'renamed_spin_loop'
  --> /home/daniela/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.9.7/src/spinwait.rs:16:9
   |
16 |         spin_loop()
   |         ^^^^^^^^^
   |
   = note: see issue #55002 <https://github.com/rust-lang/rust/issues/55002> for more information

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `parking_lot_core`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

```
```


### Your operating system and version

Nixos 22.11

### Your Python version (`python --version`)

3.9.13

### Your Rust version (`rustc --version`)

rustc 1.48.0 (7eac88abb 2020-11-16)

### Your PyO3 version

0.18.1

### How did you install python? Did you use a virtualenv?

I've installed python using a nix derivation

### Additional Info

_No response_

**Comment by adamreichold** [comment]
Thanks for taking the time to report this. However, builds using the MSRV require careful management of the transitive dependencies using e.g. `cargo update --precise`.

You can find at complete list of the necessary adjustments in our noxfile at https://github.com/PyO3/pyo3/blob/f5f688dd68758b26e72783f7e6bba34e32959966/noxfile.py#L424

We continuously build (and test) PyO3 against our current MSRV as you can see from our CI workflow defined at https://github.com/PyO3/pyo3/blob/f5f688dd68758b26e72783f7e6bba34e32959966/.github/workflows/ci.yml#L83

I hope this information is sufficient so that you can get your build working. Feel free to ask here if you need more information.

Note that this issue is not specific to PyO3, Rust crates can generally have an MSRV that is lower than that of its dependencies as long as compatible versions of those dependencies exist. (Whether those versions are still maintained is of course a different question.)
