### ISSUE TITLE
`offset_of!` not stable in Rust v1.63.0

### ISSUE THREAD

**Issue by marcpabst** [PyO3/pyo3#4408]
### Bug Description

I think https://github.com/PyO3/pyo3/pull/4254 introduced usage of the `offset_of!` macro which is not available in the current MSRV.

### Steps to Reproduce

Build with  v1.63.0

### Your operating system and version

n/a

### Your Python version (`python --version`)

n/a

### Your Rust version (`rustc --version`)

< 1.77.0 

### Your PyO3 version

0.22.2

### How did you install python? Did you use a virtualenv?

n/a

**Comment by alex** [comment]
This only uses the offset of macro from the memoffset crate as far as I can
tell.

**Comment by marcpabst** [comment]
I'm seing a `error[E0658]: use of unstable library feature 'offset_of'`:

```
error[E0658]: use of unstable library feature 'offset_of'
   --> /Users/marc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.21.0/src/types/capsule.rs:143:26
    |
143 |         debug_assert_eq!(memoffset::offset_of!(CapsuleContents::<T, F>, value), 0);
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #106655 <https://github.com/rust-lang/rust/issues/106655> for more information
    = help: add `#![feature(offset_of)]` to the crate attributes to enable
    = note: this error originates in the macro `_memoffset__offset_of_impl` which comes from the expansion of the macro `memoffset::offset_of` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by davidhewitt** [comment]
Try running `cargo update`; looks like a possible `memoffset` issue from an older version maybe.

Also your error is from a PyO3 0.21 source file so predates #4254

**Comment by marcpabst** [comment]
Yeah, looks like it's my messed-up local toolchain which reports as a newer version than what it actually is. I suspect that in turn confuses `memoffset` - so not actually a Pyo3 issue. Sorry!
