### ISSUE TITLE
`#[pyo3(get)]` can fail to compile some types with `experimental-inspect`

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#6233]
The following minimal `lib.rs` will fail to compile on PyO3 0.29.0 with `experimental-inspect` enabled:

```rust
use std::convert::Infallible;

use pyo3::{prelude::*, types::PyString};

#[derive(Clone)]
struct RefOnly;

impl<'py> IntoPyObject<'py> for &RefOnly {
    type Target = PyString;
    type Output = Bound<'py, PyString>;
    type Error = Infallible;

    fn into_pyobject(self, py: Python<'py>) -> Result<Self::Output, Self::Error> {
        Ok(PyString::new(py, "value"))
    }
}

#[pyclass]
struct Container {
    #[pyo3(get)]
    value: RefOnly,
}
```

The error message is:

```
error[E0277]: the trait bound `RefOnly: Sealed` is not satisfied
  --> src/lib.rs:21:12
   |
21 |     value: RefOnly,
   |            ^^^^^^^ unsatisfied trait bound
   |
help: the trait `pyo3::IntoPyObject<'_>` is not implemented for `RefOnly`
      but it is implemented for `&RefOnly`
  --> src/lib.rs:8:1
   |
 8 | impl<'py> IntoPyObject<'py> for &RefOnly {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = help: for that trait implementation, expected `&RefOnly`, found `RefOnly`
   = note: required for `RefOnly` to implement `Sealed`
note: required by a bound in `pyo3::impl_::introspection::PyReturnType::OUTPUT_TYPE`
  --> /Users/david/Dev/pyo3/main/src/impl_/introspection.rs:17:25
   |
17 | pub trait PyReturnType: return_type::Sealed {
   |                         ^^^^^^^^^^^^^^^^^^^ required by this bound in `PyReturnType::OUTPUT_TYPE`
18 |     /// The function return type
19 |     const OUTPUT_TYPE: PyStaticExpr;
   |           ----------- required by a bound in this associated constant
```

The root cause is (as hinted at in the error message) that we calculate the type annotation from `IntoPyObject`, but `RefOnly` doesn't implement `IntoPyObject`, only `&RefOnly` does.

cc @Tpt - I wonder if a practical fix is to extend the `PyO3GetField` private trait to have an `OUTPUT_TYPE` member, which can be derived appropriately? This seems like the best way to cover all cases without adding tons of additional machinery.

**Comment by Tpt** [comment]
Thanks! Will work on that next week

**Comment by davidhewitt** [comment]
Thank you! Looks like we have a ton of fixes coming into 0.29.1 (not all are merged yet) - I'll hold the release so that we can ship this too, it's been many weeks, I'm sure we can wait another 😂
