### ISSUE TITLE
the trait bound `Vec<[&str; 2]>: FromPyObject<'_>` is not satisfied

### ISSUE THREAD

**Issue by Crispy13** [PyO3/pyo3#3997]
Hi. I'm trying to apply the new version pyo3, 0.21.0 to my codes.

The following codes worked in 0.20, but not in 0.21.
```
#[pyfunction]
#[pyo3(signature = (chr_pos_vec))]
pub(crate) fn ebd<'a>(
    chr_pos_vec: Vec<[&str; 2]>,
) -> PyResult<VamDataVec<'a>> {
    todo!()
}
```

The error messages:
```
error[E0277]: the trait bound `Vec<[&str; 2]>: FromPyObject<'_>` is not satisfied
   --> src/tools.rs:51:18
    |
51  |     chr_pos_vec: Vec<[&str; 2]>,
    |                  ^^^ the trait `FromPyObject<'_>` is not implemented for `Vec<[&str; 2]>`, which is required by `Vec<[&str; 2]>: PyFunctionArgument<'_, '_>`
    |
    = help: the trait `FromPyObject<'py>` is implemented for `Vec<T>`
    = note: required for `Vec<[&str; 2]>` to implement `FromPyObjectBound<'_, '_>`
    = note: required for `Vec<[&str; 2]>` to implement `PyFunctionArgument<'_, '_>`
note: required by a bound in `extract_argument`
   --> /bruce_wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.21.0/src/impl_/extract_argument.rs:119:8
    |
113 | pub fn extract_argument<'a, 'py, T>(
    |        ---------------- required by a bound in this function
...
119 |     T: PyFunctionArgument<'a, 'py>,
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `extract_argument`
```

Could you tell me how to solve this? 

I read [migration guide](https://pyo3.rs/v0.21.0/migration) and [this issue](https://github.com/PyO3/pyo3/issues/3990) but I'm still stuck on it.

**Comment by davidhewitt** [comment]
I think the easiest solution is to use `chr_pos_vec: Vec<[PyBackedStr; 2]>` as your function argument.

The problem is that the `&str` extraction relies on temporary values read from the Python list. The "GIL Refs" we are moving away from made this extraction possible but had performance and safety problems that ultimately led to the need to change this.

**Comment by Crispy13** [comment]
Thanks
