### ISSUE TITLE
Wierd #[pymethods] behaviour on Python 3.11

### ISSUE THREAD

**Issue by dvolodin7** [PyO3/pyo3#2722]
### Bug Description

Porting our [Gufo Ping](https://github.com/gufolabs/gufo_ping) package to Python 3.11 I've found that PyO3 class does not exposes its methods to Python properly. Code is straightforward:

```
/// Module index
#[pymodule]
#[pyo3(name = "_fast")]
fn gufo_ping(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_class::<SocketWrapper>()?;
    Ok(())
}

/// ....
/// Python class wrapping socket implementation
#[pyclass]
pub(crate) struct SocketWrapper {
    ....
}

#[pymethods]
impl SocketWrapper {
    /// Python constructor
    #[new]
    fn new(afi: u8) -> PyResult<Self> {
        ...
    }

    /// Set default timeout, in nanoseconds
    fn set_timeout(&mut self, timeout: u64) -> PyResult<()> {
          ....
    }
   ....
```

Code works on Python 3.8-3.10. But when compiling on Python 3.11, module compiles without errors, but it is not possible to access defined methods from python:

```
SocketWrapper(4).set_timeout(1_000_000_000)
```

raises AttributeError for all methods other from constructor.

I've tried to use 

```
dir(SocketWrapper(4))
```

and get

```
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
```

On elder python versions all instance methods defined in Rust are exposed properly.

### Steps to Reproduce

1. Considering [Gufo Ping](https://github.com/gufolabs/gufo_ping) repo.
2. Using python:3.10-slim-bullseye image as base install rust 1.65.0 and run
```
python -m build --sdist --wheel
```
3. Then run testing suite
```
pytest -vv
```
4. All tests are passed
5. Switch to Using python:3.10-slim-bullseye image as base install rust 1.65.0 and run
```
python -m build --sdist --wheel
```
6. Then run testing suite
```
pytest -vv
```
7. Lots of tests are failed with AttributeError

### Backtrace

```shell
AttributeError: 'SocketWrapper' object has no attribute 'set_timeout'
```

### Your operating system and version

Linux Debian 11.5

### Your Python version (`python --version`)

Python 3.11

### Your Rust version (`rustc --version`)

1.65.0

### Your PyO3 version

0.17.3

### How did you install python? Did you use a virtualenv?

python:3.11-slim-bullseye official docker image.

**Comment by davidhewitt** [comment]
@dvolodin7 can you try running `cargo clean` after switching to 3.11 and retry? I wonder if this is related to #2724 (cc @messense)

**Comment by dvolodin7** [comment]
Tried, same error:

```
root@cb16cbf4ebec:/workspaces/gufo_ping# cargo clean
root@cb16cbf4ebec:/workspaces/gufo_ping# python -m build --sdist --wheel
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools, setuptools-rust, wheel)
* Getting build dependencies for sdist...
running egg_info
writing src/gufo_ping.egg-info/PKG-INFO
writing dependency_links to src/gufo_ping.egg-info/dependency_links.txt
writing top-level names to src/gufo_ping.egg-info/top_level.txt
reading manifest file 'src/gufo_ping.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching '__pycache__'
warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
adding license file 'LICENSE.md'
writing manifest file 'src/gufo_ping.egg-info/SOURCES.txt'
* Building sdist...
running sdist
running egg_info
writing src/gufo_ping.egg-info/PKG-INFO
writing dependency_links to src/gufo_ping.egg-info/dependency_links.txt
writing top-level names to src/gufo_ping.egg-info/top_level.txt
reading manifest file 'src/gufo_ping.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching '__pycache__'
warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
adding license file 'LICENSE.md'
writing manifest file 'src/gufo_ping.egg-info/SOURCES.txt'
running check
creating gufo_ping-0.2.3
creating gufo_ping-0.2.3/src
creating gufo_ping-0.2.3/src/gufo
creating gufo_ping-0.2.3/src/gufo/ping
creating gufo_ping-0.2.3/src/gufo_ping.egg-info
copying files to gufo_ping-0.2.3...
copying Cargo.toml -> gufo_ping-0.2.3
copying LICENSE.md -> gufo_ping-0.2.3
copying MANIFEST.in -> gufo_ping-0.2.3
copying README.md -> gufo_ping-0.2.3
copying pyproject.toml -> gufo_ping-0.2.3
copying setup.cfg -> gufo_ping-0.2.3
copying setup.py -> gufo_ping-0.2.3
copying src/icmp.rs -> gufo_ping-0.2.3/src
copying src/lib.rs -> gufo_ping-0.2.3/src
copying src/session.rs -> gufo_ping-0.2.3/src
copying src/socket.rs -> gufo_ping-0.2.3/src
copying src/gufo/ping/__init__.py -> gufo_ping-0.2.3/src/gufo/ping
copying src/gufo/ping/_fast.py -> gufo_ping-0.2.3/src/gufo/ping
copying src/gufo/ping/ping.py -> gufo_ping-0.2.3/src/gufo/ping
copying src/gufo/ping/proto.py -> gufo_ping-0.2.3/src/gufo/ping
copying src/gufo/ping/socket.py -> gufo_ping-0.2.3/src/gufo/ping
copying src/gufo_ping.egg-info/PKG-INFO -> gufo_ping-0.2.3/src/gufo_ping.egg-info
copying src/gufo_ping.egg-info/SOURCES.txt -> gufo_ping-0.2.3/src/gufo_ping.egg-info
copying src/gufo_ping.egg-info/dependency_links.txt -> gufo_ping-0.2.3/src/gufo_ping.egg-info
copying src/gufo_ping.egg-info/not-zip-safe -> gufo_ping-0.2.3/src/gufo_ping.egg-info
copying src/gufo_ping.egg-info/top_level.txt -> gufo_ping-0.2.3/src/gufo_ping.egg-info
Writing gufo_ping-0.2.3/setup.cfg
Creating tar archive
removing 'gufo_ping-0.2.3' (and everything under it)
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools, setuptools-rust, wheel)
* Getting build dependencies for wheel...
running egg_info
writing src/gufo_ping.egg-info/PKG-INFO
writing dependency_links to src/gufo_ping.egg-info/dependency_links.txt
writing top-level names to src/gufo_ping.egg-info/top_level.txt
reading manifest file 'src/gufo_ping.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching '__pycache__'
warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
adding license file 'LICENSE.md'
writing manifest file 'src/gufo_ping.egg-info/SOURCES.txt'
* Installing packages in isolated environment... (wheel)
* Building wheel...
running bdist_wheel
running build
running build_py
copying src/gufo/ping/socket.py -> build/lib.linux-x86_64-cpython-311/gufo/ping
running egg_info
writing src/gufo_ping.egg-info/PKG-INFO
writing dependency_links to src/gufo_ping.egg-info/dependency_links.txt
writing top-level names to src/gufo_ping.egg-info/top_level.txt
reading manifest file 'src/gufo_ping.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching '__pycache__'
warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
adding license file 'LICENSE.md'
writing manifest file 'src/gufo_ping.egg-info/SOURCES.txt'
running build_ext
running build_rust
cargo rustc --lib --message-format=json-render-diagnostics --manifest-path Cargo.toml --release -v --features pyo3/extension-module -- --crate-type cdylib
   Compiling libc v0.2.121
   Compiling target-lexicon v0.12.3
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.36
     Running `rustc --crate-name build_script_build --edition=2018 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/target-lexicon-0.12.3/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="default"' -C metadata=a08a1b2fc1eb34ad -C extra-filename=-a08a1b2fc1eb34ad --out-dir /workspaces/gufo_ping/target/release/build/target-lexicon-a08a1b2fc1eb34ad -C strip=debuginfo -L dependency=/workspaces/gufo_ping/target/release/deps --cap-lints allow`
...
     Running `rustc --crate-name pyo3 --edition=2018 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.17.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="extension-module"' --cfg 'feature="indoc"' --cfg 'feature="macros"' --cfg 'feature="pyo3-macros"' --cfg 'feature="unindent"' -C metadata=57c7dbfa7f05c981 -C extra-filename=-57c7dbfa7f05c981 --out-dir /workspaces/gufo_ping/target/release/deps -C strip=debuginfo -L dependency=/workspaces/gufo_ping/target/release/deps --extern cfg_if=/workspaces/gufo_ping/target/release/deps/libcfg_if-87a4133dd4c286da.rmeta --extern indoc=/workspaces/gufo_ping/target/release/deps/libindoc-d2d60881287e0da3.so --extern libc=/workspaces/gufo_ping/target/release/deps/liblibc-96d72098738a1e9f.rmeta --extern memoffset=/workspaces/gufo_ping/target/release/deps/libmemoffset-ef67701ca0d279b7.rmeta --extern parking_lot=/workspaces/gufo_ping/target/release/deps/libparking_lot-d47c34fb3ab1589d.rmeta --extern pyo3_ffi=/workspaces/gufo_ping/target/release/deps/libpyo3_ffi-ed64d026b87b1e71.rmeta --extern pyo3_macros=/workspaces/gufo_ping/target/release/deps/libpyo3_macros-2b48fc4439420555.so --extern unindent=/workspaces/gufo_ping/target/release/deps/libunindent-f80a366674f0662c.rmeta --cap-lints allow --cfg Py_3_6 --cfg Py_3_7 --cfg Py_3_8 --cfg Py_3_9 --cfg Py_3_10 --cfg Py_3_11 --cfg min_const_generics --cfg addr_of --cfg option_insert`
   Compiling gufo_ping v0.2.3 (/workspaces/gufo_ping)
     Running `rustc --crate-name gufo_ping --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type cdylib --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no --crate-type cdylib -C metadata=3a0031708c26af8e --out-dir /workspaces/gufo_ping/target/release/deps -C strip=debuginfo -L dependency=/workspaces/gufo_ping/target/release/deps --extern byteorder=/workspaces/gufo_ping/target/release/deps/libbyteorder-008dfe43ec7630d7.rlib --extern coarsetime=/workspaces/gufo_ping/target/release/deps/libcoarsetime-110b17d55e097a44.rlib --extern internet_checksum=/workspaces/gufo_ping/target/release/deps/libinternet_checksum-22eae4e6a10947f5.rlib --extern libc=/workspaces/gufo_ping/target/release/deps/liblibc-96d72098738a1e9f.rlib --extern pyo3=/workspaces/gufo_ping/target/release/deps/libpyo3-57c7dbfa7f05c981.rlib --extern rand=/workspaces/gufo_ping/target/release/deps/librand-64fc0594f4a469d4.rlib --extern socket2=/workspaces/gufo_ping/target/release/deps/libsocket2-73310face7d8929a.rlib`
    Finished release [optimized] target(s) in 1m 04s
Copying rust artifact from /workspaces/gufo_ping/target/release/libgufo_ping.so to build/lib.linux-x86_64-cpython-311/gufo/ping/_fast.cpython-311-x86_64-linux-gnu.so
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/gufo
creating build/bdist.linux-x86_64/wheel/gufo/ping
copying build/lib.linux-x86_64-cpython-311/gufo/ping/_fast.cpython-311-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/gufo/ping
copying build/lib.linux-x86_64-cpython-311/gufo/ping/__init__.py -> build/bdist.linux-x86_64/wheel/gufo/ping
copying build/lib.linux-x86_64-cpython-311/gufo/ping/_fast.py -> build/bdist.linux-x86_64/wheel/gufo/ping
copying build/lib.linux-x86_64-cpython-311/gufo/ping/socket.py -> build/bdist.linux-x86_64/wheel/gufo/ping
copying build/lib.linux-x86_64-cpython-311/gufo/ping/proto.py -> build/bdist.linux-x86_64/wheel/gufo/ping
copying build/lib.linux-x86_64-cpython-311/gufo/ping/ping.py -> build/bdist.linux-x86_64/wheel/gufo/ping
running install_egg_info
Copying src/gufo_ping.egg-info to build/bdist.linux-x86_64/wheel/gufo_ping-0.2.3-py3.11.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/gufo_ping-0.2.3.dist-info/WHEEL
creating '/workspaces/gufo_ping/dist/tmpew07l7_4/gufo_ping-0.2.3-cp311-cp311-linux_x86_64.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'gufo/ping/__init__.py'
adding 'gufo/ping/_fast.cpython-311-x86_64-linux-gnu.so'
adding 'gufo/ping/_fast.py'
adding 'gufo/ping/ping.py'
adding 'gufo/ping/proto.py'
adding 'gufo/ping/socket.py'
adding 'gufo_ping-0.2.3.dist-info/LICENSE.md'
adding 'gufo_ping-0.2.3.dist-info/METADATA'
adding 'gufo_ping-0.2.3.dist-info/WHEEL'
adding 'gufo_ping-0.2.3.dist-info/top_level.txt'
adding 'gufo_ping-0.2.3.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built gufo_ping-0.2.3.tar.gz and gufo_ping-0.2.3-cp311-cp311-linux_x86_64.whl



root@cb16cbf4ebec:/workspaces/gufo_ping# python examples/ping.py 127.0.0.1
PING 127.0.0.1: 64 bytes
Traceback (most recent call last):
  File "/workspaces/gufo_ping/examples/ping.py", line 33, in <module>
    asyncio.run(main(sys.argv[1]))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/workspaces/gufo_ping/examples/ping.py", line 11, in main
    async for r in ping.iter_rtt(address):
  File "/workspaces/gufo_ping/src/gufo/ping/ping.py", line 195, in iter_rtt
    sock = self.__get_socket(addr)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/gufo_ping/src/gufo/ping/ping.py", line 120, in __get_socket
    sock = PingSocket(
           ^^^^^^^^^^^
  File "/workspaces/gufo_ping/src/gufo/ping/socket.py", line 65, in __init__
    self.__sock.set_timeout(int(timeout * NS))
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SocketWrapper' object has no attribute 'set_timeout'
root@cb16cbf4ebec:/workspaces/gufo_ping# 
```

**Comment by dvolodin7** [comment]
Also tried to remove all build artifacts with no result

**Comment by davidhewitt** [comment]
You have a `_fast.py`  file which looks like it will clash with your rust code. Is that meant to be a `_fast.pyi`?
