### ISSUE TITLE
IndexMap 2.x doesn't seem to implement FromPyObject in PyO3 0.20.x

### ISSUE THREAD

**Issue by hjorne** [PyO3/pyo3#3880]
### Bug Description

```rust
#[pyfunction]
pub fn use_index_map(map: IndexMap<String, String>) -> bool {
    true
}
```

This will compile with pyo3 0.20.2 and indexmap 1.9.3, but not indexmap 2.0.0

### Steps to Reproduce

1. Create the above function `use_index_map`
2. Set the version of pyo3 to be 0.20.2
3. Set the version of indexmap to be 2.0.0
4. Compile

### Backtrace

```shell
error[E0277]: the trait bound `IndexMap<std::string::String, std::string::String>: PyClass` is not satisfied
  --> ...
   |
36 | pub fn use_index_map(map: IndexMap<String, String>) -> bool {
   |                           ^^^^^^^^ the trait `PyClass` is not implemented for `IndexMap<std::string::String, std::string::String>`
   |
   = help: the trait `PyClass` is implemented for `Core`
   = note: required for `IndexMap<std::string::String, std::string::String>` to implement `FromPyObject<'_>`
   = note: required for `IndexMap<std::string::String, std::string::String>` to implement `PyFunctionArgument<'_, '_>`
note: required by a bound in `extract_argument`
  --> /.../.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.2/src/impl_/extract_argument.rs:72:8
   |
66 | pub fn extract_argument<'a, 'py, T>(
   |        ---------------- required by a bound in this function
...
72 |     T: PyFunctionArgument<'a, 'py>,
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `extract_argument`
```
```


### Your operating system and version

MacOS 14.2.1

### Your Python version (`python --version`)

Python 3.11.6

### Your Rust version (`rustc --version`)

rustc 1.76.0 (07dca489a 2024-02-04)

### Your PyO3 version

0.20.2

### How did you install python? Did you use a virtualenv?

brew

### Additional Info

_No response_

**Comment by adamreichold** [comment]
We should be compatible with `indexmap` version 2.x, i.e. our version specification is `>= 1.6, < 3`. However, with these ranges spanning incompatible versions, Cargo sometimes does not unify multiple dependencies.

Could you check e.g. the output of `cargo tree` whether `pyo3` depends on a different version of `indexmap` than the one you are using via your direct dependency?

**Comment by adamreichold** [comment]
Also make sure you have enabled the `indexmap` feature of `pyo3` which is required as the support is optional and not enabled by default.

I just tested this using a newly setup project where it does seem to work.

**Comment by victorteokw** [comment]
IndexMap 2.2.5 doesn't work with Pyo3
```rust
the trait `IntoPy<Py<PyAny>>` is not implemented for `IndexMap<std::string::String, std::string::String>`
```

**Comment by davidhewitt** [comment]
Try running `cargo update` any retry. Check you are on the newest PyO3 version

**Comment by victorteokw** [comment]
Hi @davidhewitt, 0.20.2 doesn't support it. 0.20.3 is unusable, when deploying, it tries to find Python 3.13.
So will not upgrade to 0.20.3. Wait for a new version to fix the build in CI bug.

**Comment by davidhewitt** [comment]
See https://github.com/PyO3/maturin/issues/1960#issuecomment-1969773463

**Comment by davidhewitt** [comment]
I believe that this should be resolved by running `cargo update` where relevant, closing.
