### PR TITLE
Fix missing `std::sync::atomic::Ordering` import for targets without atomic64

### PR DESCRIPTION
**Pull request by rara64**
This PR resolves an issue introduced in commit 5589b17 where builds for targets without 64-bit atomics will fail with an undeclared type error.

`std::sync::atomic::Ordering` should be imported unconditionally in the use std::{ ... } block.

#### Build output from armel (32-bit architecture):
```bash
Compiling pyo3 v0.28.0 (/pyo3)
Compiling pyo3-macros v0.28.0 (/pyo3/pyo3-macros)
error[E0433]: failed to resolve: use of undeclared type `Ordering`
   --> src/impl_/pymodule.rs:125:21
    |
125 |                     Ordering::SeqCst,
    |                     ^^^^^^^^ use of undeclared type `Ordering`
    |
help: consider importing one of these enums
    |
3   + use std::cmp::Ordering;
    |
3   + use std::sync::atomic::Ordering;
    |
3   + use portable_atomic::Ordering;
    |

error[E0433]: failed to resolve: use of undeclared type `Ordering`
   --> src/impl_/pymodule.rs:126:21
    |
126 |                     Ordering::SeqCst,
    |                     ^^^^^^^^ use of undeclared type `Ordering`
    |
help: consider importing one of these enums
    |
3   + use std::cmp::Ordering;
    |
3   + use std::sync::atomic::Ordering;
    |
3   + use portable_atomic::Ordering;
    |

For more information about this error, try `rustc --explain E0433`.
error: could not compile `pyo3` (lib) due to 2 previous errors
```

#### Affected releases:
- PyO3 0.28.0

### CODE REVIEW

**Comment by alex** [comment]
Ooops, I think there's some cfg twiddling needing

File: src/impl_/pymodule.rs [hunk 1]
```diff
@@ -5,6 +5,7 @@ use std::{
     ffi::CStr,
     marker::PhantomData,
     os::raw::{c_int, c_void},
+    sync::atomic::Ordering,
```
Comment (Tpt) [inline src/impl_/pymodule.rs]: I think you need to gate it with
```rust
#[cfg(all(
    not(any(PyPy, GraalPy)),
    Py_3_9,
    not(all(windows, Py_LIMITED_API, not(Py_3_10)))
))]
```

**Comment by rara64** [comment]
> Ooops, I think there's some cfg twiddling needing

Yep, I'm on it.
