### ISSUE TITLE
Version 0.5.1 breaks SemVer guarantees

### ISSUE THREAD

**Issue by jonasbb** [PyO3/pyo3#285]
## 🐛 Bug Reports

When reporting a bug, please provide the following information. If this is not a bug report you can just discard this template.

### 🌍 Environment

 - Your operating system and version: Fedora 29
 - Your python version: 3.7
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: System version
 - Your rust version (`rustc --version`): rustc 1.32.0-nightly (f1e2fa8f0 2018-11-20)
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` Unrelated to master

### 💥 Reproducing

The following program fails to compile with version 0.5.1 but compiles with 0.5.0. This violates semver guarantees.

```rust
#![feature(specialization)]

extern crate pyo3;

use pyo3::prelude::*;

#[pyclass(name=Sequence)]
pub struct PySequence {}

#[pymethods]
impl PySequence {
    #[new]
    pub fn __new__(obj: &PyRawObject) -> PyResult<()> {
        obj.init(|_| PySequence {})
    }
}
```

The following error is reported while compiling with version 0.5.1:

```
error[E0593]: closure is expected to take 0 arguments, but it takes 1 argument
  --> src/lib.rs:14:13
   |
14 |         obj.init(|_| PySequence {})
   |             ^^^^ --- takes 1 argument
   |             |
   |             expected closure that takes 0 arguments
```
Judging by the [Changelog](https://github.com/PyO3/pyo3/blob/master/CHANGELOG.md), the changes for #94 got released as part of version 0.5.1 even though they should still be unreleased.

I suggest version 0.5.1 should be yanked from crates.io and replaces with either a correct version for the 0.5 branch or release a new 0.6, which is allowed to introduce breaking changes.

**Comment by konstin** [comment]
Thank you, I apparently failed with git and pulled the base branch of #281 in. I've yanked 0.5.1 and released 0.5.2

**Comment by kngwyu** [comment]
Wait..
@konstin 
You mean 0.5.2 doesn't include breaking changes like #265?

**Comment by jonasbb** [comment]
@konstin Thank you for the quick response.

**Comment by konstin** [comment]
@kngwyu Yes, I've only backported #281

**Comment by kngwyu** [comment]
I see, thanks.
