### PR TITLE
fix `#[pyfunction]` being marked `METH_STATIC`

### LINKED ISSUE #6426: `#[pyfunction]` gets `METH_STATIC` since 0.28, which makes calls slower on CPython 3.11+
### Bug Description

Since PyO3 0.28, every module-level `#[pyfunction]` is created with the `METH_STATIC` flag. A function with one parameter has `ml_flags` `0xa2` (`METH_FASTCALL | METH_KEYWORDS | METH_STATIC`). With PyO3 0.27.2 it has `0x82`.

The flag has two effects:

- `function.__self__` is `None`. With 0.27.2 it is the module, as it is for CPython's own builtin functions such as `math.sqrt`.
- On CPython 3.11 and newer, a call of a function that has parameters and no `**kwargs` is about 2 to 4 ns slower. For a function with an empty body this is 10 to 21%. Functions without parameters and functions with `**kwargs` are not slower. CPython 3.9 and 3.10 are not affected.

I found this while benchmarking [fastcrc](https://github.com/overcat/fastcrc/tree/main/benchmarks) after upgrading PyO3 from 0.26 to 0.29.2.

### Steps to Reproduce

A reproduction is at https://github.com/overcat/pyo3-meth-static-repro. It defines pairs of functions with empty bodies. One function of each pair is a plain `#[pyfunction]`. The other one uses `pass_module`, which does not get the flag, and is the control.

```sh
git clone https://github.com/overcat/pyo3-meth-static-repro
cd pyo3-meth-static-repro
python -m venv .venv
.venv/bin/pip install .
.venv/bin/python repro.py
```

Output with CPython 3.14.6 and PyO3 0.29.2:

```text
               plain #[pyfunction]             #[pyfunction(pass_module)]
               ml_flags  __self__  ns/call     ml_flags  __self__  ns/call     difference
no parameters  0x0024    None         13.1     0x0004    module       13.0      +0.1 ns   +1%
one parameter  0x00a2    None         19.6     0x0082    module       16.4      +3.3 ns  +20%
**kwargs       0x0023    None         16.8     0x0003    module       16.7      +0.1 ns   +1%

0x0020 = METH_STATIC
```

With PyO3 0.27.2, both columns show the same flags, `__self__` is the module in both, and the differences are 0.0 ns.

### Your operating system and version

Linux Mint 22.3 (kernel 7.0.0-31-generic, x86-64)

### Your Python version (`python --version`)

Python 3.14.6

### Your Rust version (`rustc --version`)

rustc 1.98.0 (88d9e12ae 2026-08-18)

### Your PyO3 version

0.29.2 (also 0.28.2 and main at cb456da1; 0.27.2 is not affected)

### How did you install python? Did you use a virtualenv?

mise (a precompiled python-build-standalone build), in a virtualenv created with "python -m venv"

### Additional Info

This was introduced by #5581. The README of [the reproduction](https://github.com/overcat/pyo3-meth-static-repro) explains the cause in PyO3 and in CPython. It also has the results for several PyO3 and CPython versions, the instruction counts and a workaround.

There is a candidate fix with a test: https://github.com/overcat/pyo3/commit/b3d1fd3277ee15d25943593aaab2cf17d20e7198. If you agree with the approach, I can turn it into a PR.

### PR DESCRIPTION
**Pull request by overcat**
Fixes #6426.

Since #5581 the `METH_CLASS` / `METH_STATIC` selection lives in `FnSpec::get_methoddef`, and a plain `#[pyfunction]` has `FnType::FnStatic` too, so it got `METH_STATIC`. This moves the selection back into `impl_py_method_def`, which only `#[pymethods]` uses.

### CODE REVIEW

File: tests/test_pyfunction.rs [hunk 1]
```diff
@@ -805,3 +805,43 @@ fn test_pyfunction_multiple_warnings() {
         ]
     );
 }
+
+#[test]
+#[cfg(not(PyPy))] // PyPy does not implement `PyCFunction_GetFlags`
```
Comment (davidhewitt) [inline tests/test_pyfunction.rs]: Looks like this is changed in pypy 3.12; can you please amend the FFI definition and adjust the test to also run on pypy 3.12 please. Fine to correct the FFI definition in this PR IMO; ideally if any others from that header also missing for PyPy please enable then too.

https://github.com/pypy/pypy/tree/py3.12/pypy/module/cpyext/include#L85

**Review by davidhewitt — COMMENTED** [review]
Thanks; one comment regarding PyPy coverage.

File: tests/test_pyfunction.rs (hunk 1 above)
Comment (overcat) [reply tests/test_pyfunction.rs]: Hi @davidhewitt, thanks for the suggestion! Addressed in c38ebc2

**Comment by overcat** [comment]
> ## Merging this PR will **improve performance by 15.27%**
> `⚡ 1` improved benchmark `✅ 142` untouched benchmarks `⏩ 6` skipped benchmarks[1](#user-content-fn-skipped-eda736b54d00753c75de29a91d9a0e72)
> 
> ### Performance Changes
> Benchmark	`BASE`	`HEAD`	Efficiency
> ⚡	[`test_positional_only_batched_rs`](https://app.codspeed.io/PyO3/pyo3/branches/overcat%3Afix-pyfunction-meth-static?uri=pytests%2Ftests%2Ftest_pyfunctions.py%3A%3Atest_positional_only_batched_rs&runnerMode=Simulation&utm_source=github&utm_medium=comment-v2&utm_content=benchmark)	1,091 µs	946.5 µs	+15.27%
> Tip
> 
> Curious why performance improved? Comment `@codspeedbot explain why performance improved` on this PR, or directly use the [CodSpeed MCP](https://codspeed.io/docs/ai/mcp?utm_source=github&utm_medium=comment-v2&utm_content=mcp_tip_improvement) with your agent.
> 
> Comparing `overcat:fix-pyfunction-meth-static` ([77fd046](https://github.com/PyO3/pyo3/commit/77fd0461b6508c7d51eecb643d5ce75b755b3457)) with `main` ([13bcb33](https://github.com/PyO3/pyo3/commit/13bcb3363e27c98391b91592782313646d87aac3))
> 
> [ Open in CodSpeed ](https://app.codspeed.io/PyO3/pyo3/branches/overcat%3Afix-pyfunction-meth-static?utm_source=github&utm_medium=comment-v2&utm_content=button)
> ## Footnotes
> 1. 6 benchmarks were skipped, so the baseline results were used instead. If they were deleted from the codebase, [click here and archive them to remove them from the performance reports](https://app.codspeed.io/PyO3/pyo3/branches/overcat%3Afix-pyfunction-meth-static?q=is%3Askipped&utm_source=github&utm_medium=comment-v2&utm_content=archive). [↩](#user-content-fnref-skipped-eda736b54d00753c75de29a91d9a0e72)

codspeed reported performance changes.

**Review by davidhewitt — APPROVED** [review]
Thanks for the comprehensive fix
