### ISSUE TITLE
Avoid PyUnstable* API functions on PyPy

### ISSUE THREAD

**Issue by mattip** [PyO3/pyo3#6244]
### Bug Description

I have started working on pypy for python3.12 and fail tests because `PyUnstable_InterpreterFrame_GetCode` is missing.

PyPy is unlikely to implement `PyUnstable_InterpreterFrame_GetCode` and other `PyUnstable` C-API interfaces going forward. Would that be a major incompatibility? As far as I can tell, it is used for debuggers and not for common code.

### Steps to Reproduce

Test with pypy-3.12-nightly as I do in [pypy/binary-testing](https://github.com/pypy/binary-testing/actions/runs/30212546282/job/89821126491)

### Backtrace

```shell
error[E0425]: cannot find type `_PyInterpreterFrame` in this scope
  --> pyo3-ffi/src/cpython/pyframe.rs:69:60
   |
69 |     pub fn PyUnstable_InterpreterFrame_GetCode(frame: *mut _PyInterpreterFrame) -> *mut PyObject;
   |                                                            ^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `_PyInterpreterFrame` in this scope
  --> pyo3-ffi/src/cpython/pyframe.rs:72:61
   |
72 |     pub fn PyUnstable_InterpreterFrame_GetLasti(frame: *mut _PyInterpreterFrame) -> c_int;
   |                                                             ^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `_PyInterpreterFrame` in this scope
  --> pyo3-ffi/src/cpython/pyframe.rs:75:60
   |
75 |     pub fn PyUnstable_InterpreterFrame_GetLine(frame: *mut _PyInterpreterFrame) -> c_int;
   |                                                            ^^^^^^^^^^^^^^^^^^^ not found in this scope
```

### Your operating system and version

ubuntu 26.04

### Your Python version (`python --version`)

pypy 3.12

### Your Rust version (`rustc --version`)

rustc 1.97.1

### Your PyO3 version

HEAD

### How did you install python? Did you use a virtualenv?

from the actions/setup-python

### Additional Info

Thanks!

**Comment by ngoldbaum** [comment]
I think fixing this is just a matter of excluding these functions from the FFI bindings for PyPy.
