### ISSUE TITLE
Tips on handling `ffi-check`?

### ISSUE THREAD

**Issue by clin1234** [PyO3/pyo3#4908]
In my fork, when running CI tests, against Python 3.14, errors spew in the form of these:
```
error[E0609]: no field `ob_base` on type `_PyGenObject`
  --> src/main.rs:45:13
   |
45 |             pyo3_ffi_check_macro::for_all_fields!($name, check_field);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
70 |     pyo3_ffi_check_macro::for_all_structs!(check_struct);
   |     ---------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `pyo3_ffi_check_macro::for_all_fields` which comes from the expansion of the macro `pyo3_ffi_check_macro::for_all_structs` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0609]: no field `gi_weakreflist` on type `_PyGenObject`
  --> src/main.rs:45:13
   |
45 |             pyo3_ffi_check_macro::for_all_fields!($name, check_field);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
70 |     pyo3_ffi_check_macro::for_all_structs!(check_struct);
   |     ---------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `pyo3_ffi_check_macro::for_all_fields` which comes from the expansion of the macro `pyo3_ffi_check_macro::for_all_structs` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0609]: no field `gi_name` on type `_PyGenObject`
  --> src/main.rs:45:13
   |
45 |             pyo3_ffi_check_macro::for_all_fields!($name, check_field);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
70 |     pyo3_ffi_check_macro::for_all_structs!(check_struct);
   |     ---------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `pyo3_ffi_check_macro::for_all_fields` which comes from the expansion of the macro `pyo3_ffi_check_macro::for_all_structs` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0609]: no field `gi_qualname` on type `_PyGenObject`
  --> src/main.rs:45:13
   |
45 |             pyo3_ffi_check_macro::for_all_fields!($name, check_field);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
70 |     pyo3_ffi_check_macro::for_all_structs!(check_struct);
   |     ---------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `pyo3_ffi_check_macro::for_all_fields` which comes from the expansion of the macro `pyo3_ffi_check_macro::for_all_structs` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0609]: no field `gi_exc_state` on type `_PyGenObject`
  --> src/main.rs:45:13
   |
45 |             pyo3_ffi_check_macro::for_all_fields!($name, check_field);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
70 |     pyo3_ffi_check_macro::for_all_structs!(check_struct);
   |     ---------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `pyo3_ffi_check_macro::for_all_fields` which comes from the expansion of the macro `pyo3_ffi_check_macro::for_all_structs` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0609]: no field `gi_origin_or_finalizer` on type `_PyGenObject`
  --> src/main.rs:45:13
   |
45 |             pyo3_ffi_check_macro::for_all_fields!($name, check_field);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
70 |     pyo3_ffi_check_macro::for_all_structs!(check_struct);
   |     ---------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `pyo3_ffi_check_macro::for_all_fields` which comes from the expansion of the macro `pyo3_ffi_check_macro::for_all_structs` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0609]: no field `gi_hooks_inited` on type `_PyGenObject`
  --> src/main.rs:45:13
   |
45 |             pyo3_ffi_check_macro::for_all_fields!($name, check_field);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
70 |     pyo3_ffi_check_macro::for_all_structs!(check_struct);
   |     ---------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `pyo3_ffi_check_macro::for_all_fields` which comes from the expansion of the macro `pyo3_ffi_check_macro::for_all_structs` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0609]: no field `gi_closed` on type `_PyGenObject`
  --> src/main.rs:45:13
   |
45 |             pyo3_ffi_check_macro::for_all_fields!($name, check_field);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
70 |     pyo3_ffi_check_macro::for_all_structs!(check_struct);
   |     ---------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `pyo3_ffi_check_macro::for_all_fields` which comes from the expansion of the macro `pyo3_ffi_check_macro::for_all_structs` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0609]: no field `gi_running_async` on type `_PyGenObject`
  --> src/main.rs:45:13
   |
45 |             pyo3_ffi_check_macro::for_all_fields!($name, check_field);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
70 |     pyo3_ffi_check_macro::for_all_structs!(check_struct);
   |     ---------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `pyo3_ffi_check_macro::for_all_fields` which comes from the expansion of the macro `pyo3_ffi_check_macro::for_all_structs` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0609]: no field `gi_frame_state` on type `_PyGenObject`
  --> src/main.rs:45:13
   |
45 |             pyo3_ffi_check_macro::for_all_fields!($name, check_field);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
70 |     pyo3_ffi_check_macro::for_all_structs!(check_struct);
   |     ---------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `pyo3_ffi_check_macro::for_all_fields` which comes from the expansion of the macro `pyo3_ffi_check_macro::for_all_structs` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0609]: no field `gi_iframe` on type `_PyGenObject`
  --> src/main.rs:45:13
   |
45 |             pyo3_ffi_check_macro::for_all_fields!($name, check_field);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
70 |     pyo3_ffi_check_macro::for_all_structs!(check_struct);
   |     ---------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `pyo3_ffi_check_macro::for_all_fields` which comes from the expansion of the macro `pyo3_ffi_check_macro::for_all_structs` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0609]: no field `_padding` on type `_object`
  --> src/main.rs:45:13
   |
45 |             pyo3_ffi_check_macro::for_all_fields!($name, check_field);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
70 |     pyo3_ffi_check_macro::for_all_structs!(check_struct);
   |     ---------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `pyo3_ffi_check_macro::for_all_fields` which comes from the expansion of the macro `pyo3_ffi_check_macro::for_all_structs` (in Nightly builds, run with -Z macro-backtrace for more info)
```
Reproducible by running `cargo run --manifest-path=pyo3-ffi-check/Cargo.toml`

Any tips derived from adding prior CPython releases would be appreciated.

**Comment by clin1234** [comment]
For context, compare the definition of `PyGenObject` [in 3.14](https://github.com/python/cpython/blob/main/Include/cpython/genobject.h#L12) vs [in 3.13](https://github.com/python/cpython/blob/3.13/Include/cpython/genobject.h#L14-L34)

**Comment by ngoldbaum** [comment]
We generally don't add support for new Python versions until the first beta, since the API and ABI aren't stable until then.

The way to fix this is to add support for 3.14 in pyo3-ffi and update the FFI definitions.

That said, because of #4904 I think there's a case to be made to do that a little early this year so we can add TSAN testing on the free-threaded build using 3.14, which has a number of thread safety fixes that haven't been backported to 3.13.

**Comment by ngoldbaum** [comment]
I think I'm going to open and maintain a draft PR people can use to test Python 3.14 against. That way we can quickly merge the PR when 3.14 beta 1 comes out.

**Comment by clin1234** [comment]
> I think I'm going to open and maintain a draft PR people can use to test Python 3.14 against. That way we can quickly merge the PR when 3.14 beta 1 comes out.

I already have a PR: #4811

**Comment by clin1234** [comment]
Albeit still needs fixing FFI...

**Comment by ngoldbaum** [comment]
Ah missed you'd been pushing on that. Do you mind if I push to your PR?

**Comment by clin1234** [comment]
Sure, though my PR adds 3.14 for testing in CI, and the FFI test is a vexing pain in the collective posterior of all pyo3 developers...

**Comment by ngoldbaum** [comment]
The last push fixes ffi-check on the free-threaded build but unfortunately it breaks it on the GIL-enabled build.

@davidhewitt it looks like CPython made a change that breaks ffi-check, similar to how it was broken in Python 3.12 - `ob_refcnt` changed representation once again. Now it's a union that contains an inline anonymous struct and I'm not sure how to modify the `ffi-check` macro to account for this.

See [here](https://github.com/python/cpython/blob/6c450f44c283c61d0e1ada05ead9524a1fe97962/Include/object.h#L122-L137) inside CPython for what I'm talking about.

In ffi-check there's this code:

https://github.com/PyO3/pyo3/blob/241080aeba3e97f29ac2617cd89c0e26563d6703/pyo3-ffi-check/macro/src/lib.rs#L148-L154

Do you happen to know how I should I modify it now that there's an inline struct in the union as well?

**Comment by ngoldbaum** [comment]
Let's close this since the issues with ffi-check have been resolved in the PR. I'm happy to share more about how I was working with it to debug ffi issues, but I was more or less just reading the error messages and going from there to what was wrong in the FFI.
