### PR TITLE
provide an opt-out of raw-dylib

### LINKED ISSUE #6157: 0.28 raw-dylib linking regressed MSYS2/MinGW (libpython3X.dll vs python3X.dll)
## Summary

PyO3 0.28 (PR #5866) switched Windows linking to Rust's `raw-dylib` and hardcoded the imported DLL name as `python3X.dll`. This regressed MSYS2/MinGW (`*-pc-windows-gnu`) downstream builds, where the Python DLL is named `libpython3X.dll` (Unix-style `lib` prefix). Every Python C-API symbol now comes back undefined at link time.

This was already flagged by @ognevny on the merged PR but doesn't have a tracking issue:
https://github.com/PyO3/pyo3/pull/5866#issuecomment-4702708928

> hi, this change seem to regress MINGW downstream builds, probably because we use `libpython3.dll` library (it uses the lib prefix like any other UNIX environment)

The previous escape hatch (`generate-import-lib`) is now a deprecated no-op per the 0.28 changelog, so downstreams have no way to opt out aside from pinning `pyo3 = "0.27.x"`.

## Downstream impact

- **blake3-py 1.0.9** (which bumped to pyo3 0.28): https://github.com/oconnor663/blake3-py/issues/109
- **borgbackup CI on MSYS2 UCRT64**, failing log: https://github.com/borgbackup/borg/actions/runs/27977945398/job/82800454532
- The matching borg build on **pyo3 0.27 / blake3-py 1.0.8** succeeds on the same runner: https://github.com/borgbackup/borg/actions/runs/27978763145/job/82803271025

Truncated link error from the failing log:

```
ld.exe: ...libpyo3-*.rlib: undefined reference to `PyUnicode_FromStringAndSize'
ld.exe: ...libpyo3-*.rlib: undefined reference to `Py_GenericAlias'
ld.exe: ...libpyo3-*.rlib: undefined reference to `PyDict_New'
... (many more)
collect2.exe: error: ld returned 1 exit status
```

## Proposed direction

Emit the `lib`-prefixed DLL name in `extern_python_dll!` / the `raw-dylib` import on `*-pc-windows-gnu` targets when the Python install is the MSYS2-style one — or expose a build-script knob so downstreams can override the import name.

### PR DESCRIPTION
**Pull request by davidhewitt**
This is my attempt to fix #6157 

Where this differs from #6164 and #6182:
- I don't try to extend raw-dylib linking to mingw for now, instead I make PyO3 fall back to requiring the full import lib.
- I don't try to add "lib" prefix, unlike #6164 (this is done automatically by the gnu linker)
- Both PRs claim that mixed C/Rust projects might need the full import library; rather than guess at when this should happen I introduce `PYO3_USE_RAW_DYLIB=0` opt-out.

I verified this by hand on a windows box in a mingw environment; it seems to work correctly where `main` is broken.

### CODE REVIEW

**Comment by davidhewitt** [comment]
cc @chirizxc - I think by introducing a fallback to using the import lib (i.e. the "old" behaviour) this might be a better route to go down compared to #6164? Thanks for that PR and sorry I was so slow to get deep into it.

**Comment by messense** [comment]
Providing a opt-out sounds good to me. Note that I did also verify a revision of #6182 on github actions in https://github.com/messense/pyo3/actions/runs/28695802239

**Comment by chirizxc** [comment]
> cc @chirizxc - I think by introducing a fallback to using the import lib (i.e. the "old" behaviour) this might be a better route to go down compared to #6164? Thanks for that PR and sorry I was so slow to get deep into it.

I'm fine with any option (since I don't use these platforms)

@ognevny what do you think about this?

**Comment by ognevny** [comment]
lgtm

**Comment by davidhewitt** [comment]
Thanks all, I think I will proceed to merge this and ship 0.29.1. (Probably will get it live tomorrow.)

File: pyo3-build-config/src/impl_.rs [hunk 1]
```diff
@@ -2314,6 +2305,15 @@ fn default_lib_name_for_target(abi: PythonAbi, target: &Triple) -> String {
 }
 
 fn default_lib_name_windows(abi: PythonAbi, mingw: bool, debug: bool) -> Result<String> {
+    // mingw formats lib names like unix, and uses a "lib" prefix. We could let the linker
+    // handle "lib" prefix, but that means the `raw-dylib` name is incorrect (where the
+    // "lib" prefix is not automatically added).)
```
Comment (chirizxc) [inline pyo3-build-config/src/impl_.rs]:
```suggestion
    // "lib" prefix is not automatically added).
```
