### PR TITLE
fix(pyo3-macros): allow pyclass named Probe

### LINKED ISSUE #4792: Confusing error message when using #[pyclass] with a struct called Probe
### Bug Description

The following code fails to compile, with a somewhat confusing error message:

```rust
use pyo3::prelude::*;

#[pyclass]
struct Probe {}
```

The error message is:

```
error[E0782]: expected a type, found a trait
 --> src/lib.rs:4:8
  |
4 | struct Probe {}
  |        ^^^^^
  |
help: you can add the `dyn` keyword if you want a trait object
  |
4 | struct dyn Probe {}
  |        +++

For more information about this error, try `rustc --explain E0782`.
error: could not compile `pyo3-repro` (lib) due to 1 previous error
```

rust-analyzer suggests that this might be due to the `trait Probe` here:
https://github.com/PyO3/pyo3/blob/926f5cf8e427d08b0a4670d89e3b0f342c299489/src/impl_/pyclass/probes.rs#L16

I'm not sure if this can be fixed, but it would be nice to at least have a clearer error message to indicate that the struct can't be called `Probe`. 

### Steps to Reproduce

Compile the code mentioned above.

### Backtrace

_No response_

### Your operating system and version

Ubuntu 24.04

### Your Python version (`python --version`)

Python 3.12.3

### Your Rust version (`rustc --version`)

rustc 1.83.0 (90b35a623 2024-11-26)

### Your PyO3 version

0.23.3

### How did you install python? Did you use a virtualenv?

apt

### Additional Info

This was observed when updating PyO3 from version 0.21 to 0.22, so it seems to have changed in version 0.22.

### PR DESCRIPTION
**Pull request by maurosilber**
The `*` import was shadowing the name of the pyclass.

Fixes #4792.

I tested on a codebase that had one struct/pyclass named Probe, and many other structs/pyclasses.
But I'm not sure if some of the imports that I removed are necessary in other situations that I have not tested.

### CODE REVIEW

**Comment by alex** [comment]
Can you add a testcase for this so we don't regress?

**Comment by maurosilber** [comment]
I created a copy of this file, but adding a field to the `Probe` struct:
https://github.com/PyO3/pyo3/blob/3ffad5a9b2ef89c7a8fe2015bbba16b4d3a72097/tests/ui/pyclass_probe.rs#L4-L19
and then a new line with the corresponding filename here:
https://github.com/PyO3/pyo3/blob/3ffad5a9b2ef89c7a8fe2015bbba16b4d3a72097/tests/test_compile_error.rs#L95

But the test does not fail when I tried locally (before applying my changes, I mean). 🤔

File: pyo3-macros-backend/src/pyclass.rs
Comment (Icxolu) [inline pyo3-macros-backend/src/pyclass.rs]:
```suggestion
            PyClassMethodsType::Specialization => (quote! {{ use #pyo3_path::impl_::pyclass::PyMethods as _; collector.py_methods() }}, None, None),
```
I think you can put the trait in here to avoid condition compilation shinanigans.

File: pyo3-macros-backend/src/pyclass.rs [hunk 1]
```diff
@@ -3010,13 +3010,14 @@ impl<'a> PyClassImplsBuilder<'a> {
                 type BaseNativeType = #base_nativetype;
 
                 fn items_iter() -> #pyo3_path::impl_::pyclass::PyClassItemsIter {
-                    use #pyo3_path::impl_::pyclass::*;
-                    let collector = PyClassImplCollector::<Self>::new();
-                    static INTRINSIC_ITEMS: PyClassItems = PyClassItems {
+                    use #pyo3_path::impl_::pyclass::PyMethods as _;
+                    use #pyo3_path::types::PyAnyMethods as _;
```
Comment (Icxolu) [inline pyo3-macros-backend/src/pyclass.rs]:
```suggestion
```

File: src/impl_/pyclass.rs [hunk 2]
```diff
@@ -1002,7 +1002,7 @@ pub trait PyClassInventory: inventory::Collect {
 }
 
 // Items from #[pymethods] if not using inventory.
-#[cfg(not(feature = "multiple-pymethods"))]
+// #[cfg(not(feature = "multiple-pymethods"))]
```
Comment (Icxolu) [inline src/impl_/pyclass.rs]:
```suggestion
#[cfg(not(feature = "multiple-pymethods"))]
```
This needs to be reverted.

**Review by Icxolu — COMMENTED** [review]
We need to revert the commented cfg and add a newsfragment, otherwise I think this looks good.
